"""create posts and comments tables

Revision ID: b4bc145d9e6c
Revises: 
Create Date: 2026-02-11 12:27:51.170350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bc145d9e6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('author_type', sa.Enum('HUMAN', 'AI', 'BOT', name='author_type_enum'), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_author_type', 'posts', ['author_type'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('post_id', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('author_type', sa.Enum('HUMAN', 'AI', 'BOT', name='author_type_enum'), nullable=False),
    sa.Column('parent_id', sa.String(length=12), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_author_type', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
